-- CreateTable
CREATE TABLE "Transaction" (
    "id" SERIAL NOT NULL,
    "component_cnt_bet" INTEGER,
    "selection" TEXT,
    "line" DOUBLE PRECISION,
    "is_alternate" INTEGER,
    "is_inplay" INTEGER,
    "is_active" TEXT,
    "is_cashout" TEXT,
    "currency" TEXT,
    "book_risk_component" DOUBLE PRECISION,
    "book_profit_gross_component" DOUBLE PRECISION,
    "client_id" INTEGER,
    "country" TEXT,
    "state" TEXT,
    "accepted_datetime_utc" TIMESTAMP(3),
    "component_price" DOUBLE PRECISION,
    "component_prob" DOUBLE PRECISION,
    "component_num_bet" INTEGER,
    "bet_type_id" INTEGER,
    "bet_type" TEXT,
    "book_risk" DOUBLE PRECISION,
    "parlay_type_id" INTEGER,
    "book_profit_gross" DOUBLE PRECISION,
    "parlay_type" TEXT,
    "bet_price" DOUBLE PRECISION,
    "bet_prob" DOUBLE PRECISION,
    "country_id" INTEGER,
    "state_id" TEXT,
    "currency_id" INTEGER,
    "sport_id" INTEGER,
    "sport" TEXT,
    "season" INTEGER,
    "date" TIMESTAMP(3),
    "datetime_utc" TIMESTAMP(3),
    "event_id" INTEGER,
    "event_status_id" INTEGER,
    "event_type_id" INTEGER,
    "stat_type_id" INTEGER,
    "stat_type" TEXT,
    "product_id" INTEGER,
    "product" TEXT,
    "team_id" INTEGER,
    "opp_id" INTEGER,
    "team_abbr" TEXT,
    "opp_abbr" TEXT,
    "home" INTEGER,
    "player_id" INTEGER,
    "player_name" TEXT,
    "pos_id" INTEGER,
    "pos_abbr" TEXT,
    "game_played" INTEGER,
    "game_started" INTEGER,
    "actual" DOUBLE PRECISION,
    "accepted_min_before_start" DOUBLE PRECISION,
    "settled_date" TIMESTAMP(3),
    "market_duration_id" INTEGER,
    "market_duration_value" TEXT,
    "market_duration_type" TEXT,
    "bet_id_swish" TEXT,
    "component_id_swish" TEXT,
    "line_at_bet" DOUBLE PRECISION,
    "prob_norm_at_bet" DOUBLE PRECISION,
    "proj_at_bet" DOUBLE PRECISION,
    "market_suspended_id" TEXT,
    "market_suspended_description" TEXT,
    "gamestate_id" DOUBLE PRECISION,
    "gamestate" TEXT,
    "score" DOUBLE PRECISION,
    "opp_score" DOUBLE PRECISION,
    "period" DOUBLE PRECISION,
    "usage_at_bet" DOUBLE PRECISION,
    "actual_at_bet" DOUBLE PRECISION,
    "is_in_game" DOUBLE PRECISION,
    "event_time_id" INTEGER,
    "event_time_remaining" INTEGER,
    "usage_id" INTEGER,
    "orig_proj_at_bet" DOUBLE PRECISION,
    "line_diff_at_bet" DOUBLE PRECISION,
    "prob_diff_at_bet" DOUBLE PRECISION,
    "received_date" TIMESTAMP(3),
    "client_name" TEXT,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Transaction_client_name_player_name_sport_season_currency_c_idx" ON "Transaction"("client_name", "player_name", "sport", "season", "currency", "country", "is_active");
